### ISSUE TITLE
python.exe odir_inception_training_basic.py File is not Available.

### ISSUE THREAD

**Issue by mr-sheik** [JordiCorbilla/ocular-disease-intelligent-recognition-deep-learning#1]
4) Run Inception-v3
-- Basic Run of the model
**python.exe odir_inception_training_basic.py** 
while running this command I am getting **can't open file 'odir_inception_training.py': [Errno 2] No such file or directory** Please explain where I am doing wrong. Thankyou!

**Comment by JordiCorbilla** [comment]
try `odir_inception_v3_training_basic.py`.

I will update the page.
